---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: cida-centos-6.6-vbox
    driver:
      box: usgs-wsi-centos-6.6-vbox
      box_url: ftp://ftpext.usgs.gov/pub/er/wi/middleton/dblodgett/boxes/virtualbox/opscode_centos-6.6_chef-provisionerless.box
  - name: cida-centos-6.6-vmware
    driver:
      box: usgs-wsi-centos-6.6-vmware
      box_url: ftp://ftpext.usgs.gov/pub/er/wi/middleton/dblodgett/boxes/vmware/opscode_centos-6.6_chef-provisionerless.box

suites:
  - name: default
    network:
      - ["forwarded_port", {guest: 5672, host: 5672}]
      - ["forwarded_port", {guest: 15672, host: 15672}]
    run_list:
      - recipe[cida_rabbitmq::default, cida_rabbitmq::mgmt_console]
    attributes:
  - name: no_mgmt_console
    network:
      - ["forwarded_port", {guest: 5672, host: 5672}]
      - ["forwarded_port", {guest: 15672, host: 15672}]
    run_list:
      - recipe[cida_rabbitmq::default]
    attributes: