---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: 'test/integration/default/data_bags/'
  environments_path: 'test/integration/default/environments'
  client_rb:
    environment: rabbitmq

platforms:
  - name: centos-6.6

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags/'
    network:
      - ["forwarded_port", {guest: 5672, host: 5672}] # RabbitMQ Port
      - ["forwarded_port", {guest: 15672, host: 15672}] # Management Console
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[cida_rabbitmq::default]
      - recipe[cida_rabbitmq::mgmt_console]
    attributes:
