---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6-vbox
    driver:
      box: chef/centos-6.6
      box_url: chef/centos-6.6
      provider: virtualbox
  - name: centos-6.6-vmware
    driver:
      box: chef/centos-6.6
      box_url: chef/centos-6.6
      provider: vmware_fusion

suites:
  - name: default
    network:
      - ["forwarded_port", {guest: 5672, host: 5672}] # RabbitMQ Port
      - ["forwarded_port", {guest: 15672, host: 15672}] # Management Console
    run_list:
      - recipe[cida_rabbitmq::mgmt_console]
    attributes:
  - name: no_mgmt_console
    network:
      - ["forwarded_port", {guest: 5672, host: 5672}] # RabbitMQ Port
    run_list:
      - recipe[cida_rabbitmq::default]
    attributes: